name: Cache

on:
  push:
    branches:
      - main
    paths:
      - "flake.nix"
      - "flake.lock"
      - "nix/package.nix"
      - "rust-app/**"

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Connect to Cachix
        uses: cachix/cachix-action@v14
        with:
          name: openmesh
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Upload derivation to Cachix
        run: nix build --accept-flake-config | cachix push openmesh
