name: installer

on:
  push:
    tags:
      - "installer"

jobs:
  build-and-upload:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Build kexec installer
        run: nix build --accept-flake-config ./os/installer#kexec

      - name: Add kexec installer to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./result/xnodeos-kexec-installer-*.tar.gz

      - name: Build iso installer
        run: nix build --accept-flake-config ./os/installer#iso

      - name: Add iso installer to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./result/iso/xnodeos-iso-installer-*.iso
